### PR TITLE
The last thing needing implementation is the gameover screen.

### PR DESCRIPTION
**Pull request by mbadgett**
When the player dies or when they get tho the bottom right corner the game is over. Dying is a loss. Getting to the bottom right corner is a win.

### CODE REVIEW

**Comment by markfj81** [comment]
I finished the end game pic and I did spend aprox 40 min playing with code. This does work but I really don't suggest this is the final version, as it is really bad coding practice. I basically only modified the survivor file and only 1 function.
Survivor.prototype.update = function () {    if (this.health < 1) {        this.removeFromWorld = true; console.log('DEAD1');        this.over = true; this.game.over = true; this.game.win = false; AM.queueDownload("./src/img/background.jpg");AM.queueDownload("./src/img/survivor_move_handgun_sprite.png");AM.queueDownload("./src/img/survivor_handgun_idle_sprite.png");AM.queueDownload("./src/img/zombie_sprite.png");AM.queueDownload("./src/img/Glenos-G_160_bullet.png");AM.queueDownload("./src/img/3x3.png");AM.queueDownload("./src/img/3x1.png");AM.queueDownload("./src/img/1x3.png");AM.queueDownload("./src/img/zombie_attack_sprite.png");AM.queueDownload("./src/img/pickups/ammo.png");AM.queueDownload("./src/img/pickups/health.png");AM.queueDownload("./src/img/pickups/radpills.png");AM.queueDownload("./src/img/pickups/water.png");AM.queueDownload("./src/img/TitleScreen.jpg");AM.queueDownload("./src/img/endScreen.jpg");AM.queueDownload("./src/img/HUD.png"); AM.downloadAll(function () {    var canvas = document.getElementById("gameWorld");    var ctx = canvas.getContext("2d");    ctx.canvas.width  = window.innerWidth;    ctx.canvas.height = window.innerHeight;  var gameEngine = new GameEngine(); var endScreen = new GameEngine(); var gameOver = new GameEngine(); endScreen.init(ctx); endScreen.addEntity(new EndScreen(endScreen, gameEngine));  endScreen.gameEngine = gameEngine; gameEngine.gameOver = gameOver; endScreen.start("THIS endScreen");});  this.over = false; this.game.over = false; this.game.win = false;     }

```
On Tuesday, May 24, 2016 2:32 PM, mbadgett <notifications@github.com> wrote:
```

 Merged #11.—

**Comment by clalligood** [comment]
Why is there no commit/ push for this code?

**Comment by markfj81** [comment]
Because like I said this is really poor coding,  some of the worst I have done.  I didn't have much time to play with and now I'm going to a 
family dinner.  I won't be able to get back to this tonight.  I don't think this is something we should turn in but the picture is good 
Sent from Yahoo Mail on Android 

  On Wed, May 25, 2016 at 3:05 PM, Collin Alligoodnotifications@github.com wrote:  
Why is there no commit/ push for this code?

**Comment by clalligood** [comment]
So what're you're saying is your code is useless and we have to do it ourselves regardless..?

**Comment by clalligood** [comment]
Also, what graphic are you talking about? You never committed anything. Code nor graphics.

**Comment by markfj81** [comment]
I emailed the pic and the code because the code is crap and I am thinking it should be re-done, the pic is good and was emailed with code. I think I might have some time to actually try to put some time into code tomorrow. The truth is I am by far the worst coder among us and I am pretty sure either of you could code a much better way much quicker than me, but I will let you choose

```
On Wednesday, May 25, 2016 4:34 PM, Collin Alligood <notifications@github.com> wrote:
```

 Also, what graphic are you talking about? You never committed anything. Code nor graphics.—

**Comment by clalligood** [comment]
Emailed to who?

**Pull request merged**
